const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=value=>Number(value).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});let cache={subjects:[],students:[],scores:[]},scoreMode='subject',pdfImportStudentId='';
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'Não foi possível concluir a operação.');error.logs=Array.isArray(data.logs)?data.logs:[];error.userAction=data.user_action||'';throw error}return data}
async function saveScoreResult(payload){return api('/api/admin/score',{method:'POST',body:JSON.stringify(payload)})}
function closeAdminFeedback(){const dialog=$('#admin-feedback-dialog');if(!dialog)return;if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')}
function showAdminFeedback({title='Aviso',eyebrow='Aviso',message='',userAction='',logs=[],tone='info'}={}){const dialog=$('#admin-feedback-dialog'),content=$('#admin-feedback-content');if(!dialog||!content){window.alert([message,userAction].filter(Boolean).join('\n\n'));return}$('#admin-feedback-eyebrow').textContent=eyebrow;$('#admin-feedback-title').textContent=title;const logItems=(logs||[]).map(item=>{const level=String(item.level||'info').toLowerCase();return`<li class="log-${esc(level)}"><span class="log-level">${esc(level)}</span><div><div>${esc(item.message||'')}</div>${item.at?`<div class="log-meta">${esc(item.at)}</div>`:''}</div></li>`}).join('');content.innerHTML=`${message?`<p>${esc(message)}</p>`:''}${userAction?`<div class="admin-feedback-action"><strong>O que você deve fazer</strong><span>${esc(userAction)}</span></div>`:''}${logItems?`<p><strong>Detalhes para ajuste</strong></p><ul class="admin-feedback-logs">${logItems}</ul>`:''}`;dialog.dataset.tone=tone;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}
$('#admin-feedback-close')?.addEventListener('click',closeAdminFeedback);$('#admin-feedback-close-bottom')?.addEventListener('click',closeAdminFeedback);$('#admin-feedback-dialog')?.addEventListener('click',event=>{if(event.target===$('#admin-feedback-dialog'))closeAdminFeedback()});
function setupAdminTabs(){const dashboard=$('#dashboard');if(!dashboard||dashboard.dataset.tabsReady)return;dashboard.dataset.tabsReady='true';const shell=document.createElement('div'),sidebar=document.createElement('aside'),content=document.createElement('div');shell.className='admin-workspace';sidebar.className='admin-sidebar';content.className='admin-tab-content';sidebar.innerHTML=`<div class="admin-sidebar-brand"><img src="assets/escudo-efas.png" alt="Escudo da EFAS"><div><strong>Controle de Notas</strong><small>1º Pelotão</small></div></div><nav class="admin-sidebar-nav" aria-label="Seções do painel"><button type="button" class="active" data-admin-tab="notes" aria-pressed="true"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5h6M9 3h6a2 2 0 0 1 2 2v16H7V5a2 2 0 0 1 2-2Z"/><path d="m10 13 1.5 1.5L15 11"/></svg><span>Lançamento de notas</span></button><button type="button" data-admin-tab="calendar" aria-pressed="false"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4m8-4v4M3 10h18m-12 4h.01m4 0h.01m-4 3h.01m4 0h.01"/></svg><span>Calendário de provas</span></button><button type="button" data-admin-tab="ranking" aria-pressed="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 21h8m-4-4v4M7 3h10v5a5 5 0 0 1-10 0V3Z"/><path d="M5 5H3v2a4 4 0 0 0 4 4m12-6h2v2a4 4 0 0 1-4 4"/></svg><span>Ranking</span></button></nav>`;const groups=[{id:'notes',elements:['.score-mode-panel','.compact-grid','#collective-score-form','.pdf-score-import-panel','.student-subject-restriction']},{id:'calendar',elements:['#exam-form','#calendar-events-data','#calendar-import-form']},{id:'ranking',elements:['#ranking-data']}];for(const group of groups){const panel=document.createElement('section');panel.className='admin-tab-panel';panel.id=`admin-tab-${group.id}`;panel.dataset.adminTabPanel=group.id;panel.hidden=group.id!=='notes';for(const selector of group.elements){const element=$(selector);if(!element)continue;if(selector==='#calendar-events-data'){const calendarPanel=element.closest('.admin-panel');if(calendarPanel)panel.append(calendarPanel)}else if(selector==='#ranking-data'){const rankingPanel=element.closest('.admin-panel');if(rankingPanel)panel.append(rankingPanel)}else panel.append(element)}content.append(panel)}shell.append(sidebar,content);const head=$('.admin-dashboard-head'),warning=$('#initial-warning');dashboard.append(shell);if(head)content.prepend(head);if(warning)content.insertBefore(warning,content.querySelector('.admin-tab-panel'));sidebar.querySelectorAll('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>{const tab=button.dataset.adminTab;sidebar.querySelectorAll('[data-admin-tab]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});content.querySelectorAll('[data-admin-tab-panel]').forEach(panel=>panel.hidden=panel.dataset.adminTabPanel!==tab)}))}
function enforceAdminGroups(){$('#calendar-import-form')?.remove()}
function setupStudentControlTab(){const sidebar=$('.admin-sidebar'),content=$('.admin-tab-content'),studentForm=$('#student-form');if(!sidebar||!content||!studentForm||$('#admin-tab-students'))return;const panel=document.createElement('section'),button=document.createElement('button');panel.className='admin-tab-panel';panel.id='admin-tab-students';panel.dataset.adminTabPanel='students';panel.hidden=true;panel.append(studentForm);content.querySelector('#admin-tab-calendar').insertAdjacentElement('beforebegin',panel);button.type='button';button.dataset.adminTab='students';button.setAttribute('aria-pressed','false');button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"/><circle cx="9.5" cy="7" r="4"/><path d="M19 8v6m-3-3h6"/></svg><span>Controle de discentes</span>';const calendarButton=sidebar.querySelector('[data-admin-tab="calendar"]');calendarButton.insertAdjacentElement('beforebegin',button);button.addEventListener('click',()=>{sidebar.querySelectorAll('[data-admin-tab]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});content.querySelectorAll('[data-admin-tab-panel]').forEach(item=>item.hidden=item!==panel)})}
function setupNotesVisualLayout(){const panel=$('#admin-tab-notes'),scoreForm=$('#score-form'),modePanel=$('.score-mode-panel'),passwordForm=$('#password-form'),compactGrid=$('.compact-grid'),fileInput=$('#student-score-pdf');if(!panel||!scoreForm||panel.dataset.notesLayoutReady)return;panel.dataset.notesLayoutReady='true';panel.classList.add('notes-layout');const heading=document.createElement('header');heading.className='notes-page-heading';heading.innerHTML='<p class="eyebrow dark">Lançamento de notas</p><h1>Lançamento de Notas</h1><p>Selecione a disciplina, informe os resultados e salve as notas.</p>';panel.prepend(heading);if(modePanel)scoreForm.querySelector('h2')?.insertAdjacentElement('afterend',modePanel);scoreForm.classList.add('notes-result-card');panel.insertBefore(scoreForm,compactGrid);if(passwordForm)panel.append(passwordForm);if(compactGrid&&!compactGrid.children.length)compactGrid.remove();if(fileInput&&!$('#pdf-file-name')){const fileName=document.createElement('small');fileName.id='pdf-file-name';fileName.className='pdf-file-name';fileName.textContent='Nenhum arquivo selecionado';fileInput.insertAdjacentElement('afterend',fileName);fileInput.addEventListener('change',()=>fileName.textContent=fileInput.files?.[0]?.name||'Nenhum arquivo selecionado')}}
function dashboard(user){enforceAdminGroups();setupAdminTabs();setupStudentControlTab();setupNotesVisualLayout();$('#login-panel').hidden=true;$('#dashboard').hidden=false;$('#initial-warning').hidden=!user.must_change_password;loadData()}
async function check(){try{dashboard(await api('/api/admin/session'))}catch{$('#login-panel').hidden=false;$('#dashboard').hidden=true}}
$('#admin-login-form').addEventListener('submit',async e=>{e.preventDefault();try{dashboard(await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('#admin-user').value.trim(),password:$('#admin-password').value})}))}catch(error){$('#login-message').textContent=error.message}});
function bindForm(selector,path,success,preserve=[]){$(selector).addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,message=form.querySelector('.panel-message'),names=typeof preserve==='function'?preserve():preserve,kept=Object.fromEntries(names.map(name=>[name,form.elements[name]?.value||''])),payload=Object.fromEntries(new FormData(form));try{if(path==='/api/admin/score')await saveScoreResult(payload);else await api(path,{method:'POST',body:JSON.stringify(payload)});message.textContent=success;form.reset();await loadData();for(const[name,value]of Object.entries(kept))if(form.elements[name])form.elements[name].value=value;if(selector==='#score-form'){updateRule();updateObservation();$(scoreMode==='student'?'#score-subject':'#score-student').focus()}}catch(error){message.textContent=error.message}})}
bindForm('#student-form','/api/admin/student','Discente salvo com sucesso.');bindForm('#score-form','/api/admin/score','Notas salvas com sucesso.',()=>scoreMode==='student'?['student_id']:['subject_id']);
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,message=form.querySelector('.panel-message'),payload=Object.fromEntries(new FormData(form));try{await api('/api/admin/password',{method:'POST',body:JSON.stringify(payload)});message.textContent='Senha alterada com sucesso.';$('#initial-warning').hidden=true;form.reset();setTimeout(()=>$('#settings-dialog')?.close(),500)}catch(error){message.textContent=error.message}});
function isDefesaPessoal(subject){return /defesa pessoal/i.test(String(subject?.name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,''))}
function scoreTotal(score){return (isDefesaPessoal({name:score?.subject})?0:(Number(score?.exam1)||0))+(Number(score?.exam2)||0)+(Number(score?.work)||0)}
function updateRule(){const subject=cache.subjects.find(x=>String(x.id)===$('#score-subject').value);if(!subject)return;const apt=subject.grading_mode==='apt',taf=subject.grading_mode==='taf',defesa=isDefesaPessoal(subject),two=subject.exam_count===2;const exam1=$('#score-form [name=exam1]'),exam2=$('#score-form [name=exam2]'),work=$('#score-form [name=work]'),status=$('#score-form [name=status]');$('#status-label').hidden=!apt;$('.score-fields').hidden=apt;status.disabled=!apt;if(!apt)status.value='';if(apt){for(const input of [exam1,exam2,work]){input.value='';input.disabled=true}$('#score-rule').textContent='Resultado qualitativo: selecione Apto ou Inapto. Esta disciplina não integra a pontuação do ranking.';return}exam1.disabled=!taf&&(!two||defesa);exam2.disabled=false;work.disabled=false;if(exam1.disabled)exam1.value='';$('#exam1-label .field-name').textContent=taf?'1º TAF':'Avaliação Complementar (AVC)';$('#exam2-label .field-name').textContent=taf?'2º TAF':'Avaliação Final (AVF)';$('#work-label .field-name').textContent=taf?'3º TAF':'Trabalho';$('#exam1-max').textContent='(máx. 3)';$('#exam2-max').textContent=`(máx. ${taf?3:defesa?6:two?4:7})`;$('#work-max').textContent=`(máx. ${taf||defesa?4:3})`;exam1.max=3;exam2.max=taf?3:defesa?6:two?4:7;work.max=taf||defesa?4:3;$('#exam1-label').hidden=!taf&&(!two||defesa);$('#exam2-label').hidden=false;$('#score-rule').textContent=taf?'Educação Física: 1º TAF 3 pontos • 2º TAF 3 pontos • 3º TAF 4 pontos':defesa?'AVF: 6 pontos • Trabalho: 4 pontos':two?'AVC: 3 pontos • AVF: 4 pontos • Trabalho: 3 pontos':'AVF: 7 pontos • Trabalho: 3 pontos'}
function updateCalendarTypes(){const subject=cache.subjects.find(x=>x.name===$('#calendar-subject').value);if(!subject)return;const types=subject.grading_mode==='apt'?['Resultado Apto/Inapto']:subject.grading_mode==='taf'?['1º TAF','2º TAF','3º TAF']:isDefesaPessoal(subject)?['Avaliação Final (AVF)','Trabalho']:subject.exam_count===1?['Avaliação Final (AVF)','Trabalho']:['Avaliação Complementar (AVC)','Avaliação Final (AVF)','Trabalho'];$('#calendar-type').innerHTML=types.map(x=>`<option>${esc(x)}</option>`).join('')}
function formatCalendarDate(date){return new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR')}
function resetExamForm(){const form=$('#exam-form');form.reset();$('#calendar-exam-id').value='';$('#exam-form-title').textContent='Cadastrar data no calendário';$('#exam-form-submit').textContent='Cadastrar no calendário';$('#cancel-exam-edit').hidden=true;updateCalendarTypes()}
function renderCalendarEvents(){const container=$('#calendar-events-data'),events=cache.exams||[];container.innerHTML=events.length?`<div class="table-wrap"><table class="grade-table"><thead><tr><th>Data</th><th>Disciplina</th><th>Horário</th><th>Tipo</th><th>Ações</th></tr></thead><tbody>${events.map(exam=>`<tr><td>${esc(formatCalendarDate(exam.date))}</td><td><strong>${esc(exam.subject)}</strong></td><td>${esc(exam.time)}</td><td>${esc(exam.type)}</td><td><div class="table-actions"><button class="button button-dark" type="button" data-edit-exam="${esc(exam.id)}">Alterar</button><button class="button button-danger" type="button" data-delete-exam="${esc(exam.id)}">Excluir</button></div></td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhuma prova cadastrada.</p>'}
$('#exam-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,message=form.querySelector('.panel-message'),id=$('#calendar-exam-id').value,payload=Object.fromEntries(new FormData(form));try{await api(id?'/api/admin/exams/update':'/api/admin/exams',{method:'POST',body:JSON.stringify(payload)});message.textContent=id?'Prova alterada com sucesso.':'Data cadastrada no calendário.';await loadData();resetExamForm()}catch(error){message.textContent=error.message}});
$('#cancel-exam-edit').addEventListener('click',()=>{resetExamForm();$('#exam-form .panel-message').textContent='Alteração cancelada.'});
const oldObservationLabel=$('#score-observation').closest('label'),observationControls=document.createElement('div');
oldObservationLabel.remove();
observationControls.className='observation-controls';
observationControls.innerHTML=`<div class="observation-action-buttons"><button id="add-observation-button" class="button button-dark" type="button">Adicionar observação</button><button id="delete-observation-button" class="button button-danger" type="button">Excluir observação</button></div><div id="observation-editor" class="observation-editor" hidden><label>Observação individual<textarea id="independent-observation" rows="4" placeholder="Digite a informação que será exibida ao discente."></textarea></label><div class="observation-editor-actions"><button id="save-observation-button" class="button button-dark" type="button">Salvar observação</button><button id="cancel-observation-button" class="button button-outline-dark" type="button">Cancelar</button></div></div>`;
$('#score-form > .button-gold').insertAdjacentElement('afterend',observationControls);
const observationAddButton=$('#add-observation-button'),observationDeleteButton=$('#delete-observation-button'),observationEditor=$('#observation-editor'),independentObservation=$('#independent-observation');
function updateObservation(){independentObservation.value='';observationEditor.hidden=true;const disabled=!$('#score-student').value;observationAddButton.disabled=disabled;observationDeleteButton.disabled=disabled}
observationAddButton.addEventListener('click',()=>{const sid=$('#score-student').value,message=$('#score-form .panel-message');if(!sid){message.textContent='Selecione um discente antes de adicionar a observação.';return}independentObservation.value='';observationEditor.hidden=false;independentObservation.focus()});
$('#cancel-observation-button').addEventListener('click',()=>{independentObservation.value='';observationEditor.hidden=true});
$('#save-observation-button').addEventListener('click',async()=>{const sid=$('#score-student').value,observation=independentObservation.value.trim(),message=$('#score-form .panel-message'),button=$('#save-observation-button');if(!sid){message.textContent='Selecione um discente antes de salvar a observação.';return}if(!observation){message.textContent='Digite a observação antes de salvar.';independentObservation.focus();return}button.disabled=true;message.textContent='Salvando observação...';try{const result=await api('/api/admin/observation/save',{method:'POST',body:JSON.stringify({student_id:sid,observation})});const student=cache.students.find(item=>String(item.id)===String(sid));if(student)student.observation=result.observation;independentObservation.value='';observationEditor.hidden=true;message.textContent='Observação salva com sucesso.'}catch(error){message.textContent=error.message}finally{button.disabled=false}});
observationDeleteButton.addEventListener('click',async()=>{const sid=$('#score-student').value,message=$('#score-form .panel-message');if(!sid){message.textContent='Selecione um discente antes de excluir a observação.';return}const student=cache.students.find(item=>String(item.id)===String(sid));if(!window.confirm(`Excluir definitivamente a observação de ${student?.name||'este discente'}?`))return;observationDeleteButton.disabled=true;message.textContent='Excluindo observação...';try{await api('/api/admin/observation/delete',{method:'POST',body:JSON.stringify({student_id:sid})});if(student)student.observation='';independentObservation.value='';observationEditor.hidden=true;message.textContent='Observação excluída com sucesso.'}catch(error){message.textContent=error.message}finally{observationDeleteButton.disabled=false}});
function updateScoreValues(){const studentId=$('#score-student').value,subjectId=$('#score-subject').value,score=cache.scores.find(x=>String(x.student_id)===studentId&&String(x.subject_id)===subjectId),form=$('#score-form');for(const field of ['exam1','exam2','work','status']){const input=form.elements[field];if(input&&!input.disabled)input.value=score?.[field]??''}}
function openStudentDetails(studentId){const student=cache.students.find(x=>String(x.id)===String(studentId)),ranking=cache.ranking.find(x=>String(x.id)===String(studentId));if(!student)return;const scores=cache.scores.filter(x=>String(x.student_id)===String(studentId)).sort((a,b)=>a.subject.localeCompare(b.subject,'pt-BR')),content=$('#student-details-content');$('#student-details-title').textContent=student.name;content.innerHTML=`<div class="student-details-summary"><p><strong>${esc(student.rank)}</strong><span>Matrícula ${esc(student.id)}</span></p>${ranking?`<div><span>Colocação</span><strong>${ranking.position}º</strong></div><div><span>Pontos</span><strong>${fmt(ranking.points)} / ${fmt(ranking.distributed)}</strong></div><div><span>Média</span><strong>${fmt(ranking.average)}</strong></div>`:''}</div>${scores.length?`<div class="table-wrap"><table class="grade-table student-details-table"><thead><tr><th>Disciplina</th><th>AVC / 1º TAF</th><th>AVF / 2º TAF</th><th>Trabalho / 3º TAF</th><th>Total ou resultado</th></tr></thead><tbody>${scores.map(score=>{const apt=score.grading_mode==='apt',defesa=isDefesaPessoal({name:score.subject});return`<tr><td><strong>${esc(score.subject)}</strong></td><td>${apt||defesa||score.exam1==null?'—':fmt(score.exam1)}</td><td>${apt||score.exam2==null?'—':fmt(score.exam2)}</td><td>${apt||score.work==null?'—':fmt(score.work)}</td><td><strong>${apt?esc(score.status||'Não lançado'):fmt(scoreTotal(score))}</strong></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty-student-scores"><strong>Nenhuma nota lançada</strong><p>Este discente ainda não possui matérias com pontos ou resultados cadastrados.</p></div>'}${student.observation?`<div class="student-observation"><strong>Observação</strong><p>${esc(student.observation)}</p></div>`:''}`;const dialog=$('#student-details-dialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}
function closeStudentDetails(){const dialog=$('#student-details-dialog');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')}
function setScoreMode(mode){scoreMode=mode;document.querySelectorAll('.score-mode-button').forEach(button=>{const active=button.dataset.scoreMode===mode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});const collective=mode==='collective';$('#score-form').hidden=collective;$('#collective-score-form').hidden=!collective;if(mode==='student'){$('#individual-score-title').textContent='Lançamento por discente';$('#individual-score-help').textContent='O discente permanecerá selecionado após salvar; escolha a próxima matéria.';$('#score-student').focus()}else if(mode==='subject'){$('#individual-score-title').textContent='Lançamento individual por matéria';$('#individual-score-help').textContent='A matéria permanecerá selecionada após salvar; escolha o próximo discente.';$('#score-subject').focus()}else{$('#collective-subject').focus();renderCollectiveScores()}}
function updateStudentEntryToggle(enabled){const button=$('#student-entry-toggle-button'),message=$('#student-entry-toggle-message');button.dataset.enabled=String(enabled);button.classList.toggle('available',enabled);button.classList.toggle('unavailable',!enabled);button.setAttribute('aria-pressed',String(enabled));button.textContent=enabled?'Disponível':'Indisponível';message.textContent=enabled?'Os discentes podem lançar notas.':'O lançamento pelos discentes está bloqueado.';if(cache.subjects?.length)renderStudentSubjectRestriction(cache.student_subject_restriction)}
$('#student-entry-toggle-button').addEventListener('click',async e=>{const button=e.currentTarget,message=$('#student-entry-toggle-message'),enabled=button.dataset.enabled!=='true';button.disabled=true;message.textContent='Salvando configuração...';try{const result=await api('/api/admin/student-entry',{method:'POST',body:JSON.stringify({enabled})});cache.student_entry_enabled=Boolean(result.student_entry_enabled);updateStudentEntryToggle(cache.student_entry_enabled)}catch(error){message.textContent=error.message}finally{button.disabled=false}});
function renderStudentSubjectRestriction(config=cache.student_subject_restriction||{}){const enabled=Boolean(config.enabled),checkbox=$('#student-subject-restriction-enabled'),select=$('#student-subject-restriction-select'),highlight=$('#student-subject-restriction-highlight'),message=$('#student-subject-restriction-message');checkbox.checked=enabled;select.disabled=!enabled;select.innerHTML='<option value="">Selecione uma disciplina</option>'+cache.subjects.map(subject=>`<option value="${subject.id}">${esc(subject.name)}</option>`).join('');if(config.subject_id)select.value=String(config.subject_id);highlight.hidden=!enabled;highlight.textContent=enabled?`Lançamento liberado somente para esta disciplina: ${config.subject_name||select.options[select.selectedIndex]?.text||''}`:'Lançamento liberado somente para esta disciplina';message.textContent=enabled?'As demais disciplinas estão bloqueadas para os discentes.':'Todas as disciplinas estão disponíveis quando o lançamento pelo discente estiver autorizado.'}
$('#student-subject-restriction-enabled').addEventListener('change',event=>{const enabled=event.currentTarget.checked;$('#student-subject-restriction-select').disabled=!enabled;$('#student-subject-restriction-message').textContent=enabled?'Selecione uma disciplina e salve a restrição.':'Clique em Salvar restrição para liberar novamente todas as disciplinas.'});
$('#student-subject-restriction-save').addEventListener('click',async event=>{const button=event.currentTarget,enabled=$('#student-subject-restriction-enabled').checked,subjectId=$('#student-subject-restriction-select').value,message=$('#student-subject-restriction-message'),current=cache.student_subject_restriction||{};if(enabled&&!subjectId){message.textContent='Selecione uma disciplina antes de ativar a restrição.';$('#student-subject-restriction-select').focus();return}const changingSubject=Boolean(current.enabled)&&enabled&&String(current.subject_id)!==String(subjectId);if(changingSubject){const next=cache.subjects.find(subject=>String(subject.id)===String(subjectId));if(!window.confirm(`Alterar a disciplina liberada para “${next?.name||'a disciplina selecionada'}”? As demais ficarão bloqueadas para os discentes.`)){renderStudentSubjectRestriction(current);return}}button.disabled=true;message.textContent='Salvando configuração...';try{const result=await api('/api/admin/student-entry-restriction',{method:'POST',body:JSON.stringify({enabled,subject_id:enabled?subjectId:null})});cache.student_subject_restriction=result.student_subject_restriction;renderStudentSubjectRestriction(cache.student_subject_restriction);message.textContent=enabled?'Restrição salva com sucesso.':'Restrição desativada. Todas as disciplinas voltaram a ficar disponíveis.'}catch(error){message.textContent=error.message;renderStudentSubjectRestriction(current)}finally{button.disabled=false}});
function collectiveFields(subject){if(subject.grading_mode==='apt')return[{key:'status',label:'Resultado',type:'status'}];if(subject.grading_mode==='taf')return[{key:'exam1',label:'1º TAF',max:3},{key:'exam2',label:'2º TAF',max:3},{key:'work',label:'3º TAF',max:4}];if(isDefesaPessoal(subject))return[{key:'exam2',label:'Avaliação Final (AVF)',max:6},{key:'work',label:'Trabalho',max:4}];if(subject.exam_count===1)return[{key:'exam2',label:'Avaliação Final (AVF)',max:7},{key:'work',label:'Trabalho',max:3}];return[{key:'exam1',label:'Avaliação Complementar (AVC)',max:3},{key:'exam2',label:'Avaliação Final (AVF)',max:4},{key:'work',label:'Trabalho',max:3}]}
function renderCollectiveScores(){const select=$('#collective-subject'),current=select.value;if(select.options.length<=1)select.innerHTML='<option value="">Selecione</option>'+cache.subjects.map(x=>`<option value="${x.id}">${esc(x.name)} — ${x.hours} h/a</option>`).join('');if(current)select.value=current;const subject=cache.subjects.find(x=>String(x.id)===select.value),container=$('#collective-score-table'),button=$('#collective-save-button');if(!subject){container.innerHTML='';button.disabled=true;$('#collective-rule').textContent='Selecione uma disciplina para montar a tabela.';return}const fields=collectiveFields(subject);$('#collective-rule').textContent=subject.grading_mode==='apt'?'Resultado qualitativo Apto/Inapto.':fields.map(x=>`${x.label}: ${x.max} pontos`).join(' • ');container.innerHTML=cache.students.length?`<div class="table-wrap"><table class="grade-table collective-table"><thead><tr><th>Discente</th>${fields.map(field=>`<th>${esc(field.label)}${field.max?`<small class="table-sub">Máx. ${field.max}</small>`:''}</th>`).join('')}</tr></thead><tbody>${cache.students.map(student=>{const score=cache.scores.find(x=>String(x.subject_id)===String(subject.id)&&String(x.student_id)===String(student.id))||{};return`<tr data-student-id="${esc(student.id)}"><td><strong>${esc(student.name)}</strong><small class="table-sub">${esc(student.id)} • ${esc(student.rank)}</small></td>${fields.map(field=>`<td>${field.type==='status'?`<select data-field="status"><option value="">Não lançado</option><option${score.status==='Apto'?' selected':''}>Apto</option><option${score.status==='Inapto'?' selected':''}>Inapto</option></select>`:`<input data-field="${field.key}" type="number" min="0" max="${field.max}" step="0.01" inputmode="decimal" value="${score[field.key]??''}" aria-label="${esc(field.label)} de ${esc(student.name)}">`}</td>`).join('')}</tr>`}).join('')}</tbody></table></div>`:'<p>Nenhum discente cadastrado.</p>';button.disabled=!cache.students.length}
document.querySelectorAll('.score-mode-button').forEach(button=>button.addEventListener('click',()=>setScoreMode(button.dataset.scoreMode)));
$('#score-subject').addEventListener('change',()=>{updateRule();updateScoreValues()});$('#score-student').addEventListener('change',()=>{updateObservation();updateScoreValues()});$('#calendar-subject').addEventListener('change',updateCalendarTypes);$('#collective-subject').addEventListener('change',renderCollectiveScores);
async function loadData(){const data=await api('/api/admin/data');cache=data;updateStudentEntryToggle(Boolean(data.student_entry_enabled));$('#score-student').innerHTML='<option value="">Selecione</option>'+data.students.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.id)}</option>`).join('');const options=data.subjects.map(x=>`<option value="${x.id}">${esc(x.name)} — ${x.hours} h/a</option>`).join('');$('#score-subject').innerHTML='<option value="">Selecione</option>'+options;$('#calendar-subject').innerHTML=data.subjects.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — ${x.hours} h/a</option>`).join('');updateCalendarTypes();
renderCalendarEvents();
$('#ranking-data').innerHTML=data.ranking.length?`<div class="table-wrap"><table class="grade-table"><thead><tr><th>Posição</th><th>Discente</th><th>Pontos obtidos</th><th>Pontos distribuídos</th><th>Média</th><th>Observação</th></tr></thead><tbody>${data.ranking.map(x=>`<tr><td><strong>${x.position}º</strong></td><td><button class="student-name-button" type="button" data-student-details="${esc(x.id)}" aria-label="Ver notas lançadas de ${esc(x.name)}">${esc(x.name)}</button><small class="table-sub">${esc(x.id)} • Clique no nome para consultar</small></td><td>${fmt(x.points)}</td><td>${fmt(x.distributed)}</td><td>${fmt(x.average)}</td><td>${esc(x.observation)||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhum discente cadastrado.</p>'}
$('#refresh-button').addEventListener('click',loadData);$('#logout-button').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST',body:'{}'});location.reload()});
document.addEventListener('click',async event=>{const detailsButton=event.target.closest('[data-student-details]');if(detailsButton){openStudentDetails(detailsButton.dataset.studentDetails);return}const editButton=event.target.closest('[data-edit-exam]');if(editButton){const exam=cache.exams.find(item=>String(item.id)===String(editButton.dataset.editExam));if(!exam)return;$('#calendar-exam-id').value=exam.id;$('#exam-form [name=date]').value=exam.date;$('#calendar-subject').value=exam.subject;updateCalendarTypes();$('#calendar-type').value=exam.type;$('#exam-form [name=time]').value=exam.time;$('#exam-form-title').textContent='Alterar prova do calendário';$('#exam-form-submit').textContent='Salvar alteração';$('#cancel-exam-edit').hidden=false;$('#exam-form .panel-message').textContent=`Alterando: ${exam.subject}.`;$('#exam-form').scrollIntoView({behavior:'smooth',block:'center'});return}const deleteButton=event.target.closest('[data-delete-exam]');if(deleteButton){const exam=cache.exams.find(item=>String(item.id)===String(deleteButton.dataset.deleteExam));if(!exam||!window.confirm(`Excluir a prova “${exam.subject}” de ${formatCalendarDate(exam.date)}?`))return;deleteButton.disabled=true;try{await api('/api/admin/exams/delete',{method:'POST',body:JSON.stringify({id:exam.id})});await loadData();$('#exam-form .panel-message').textContent='Prova excluída do calendário.';if(String($('#calendar-exam-id').value)===String(exam.id))resetExamForm()}catch(error){$('#exam-form .panel-message').textContent=error.message;deleteButton.disabled=false}}});$('#student-details-close').addEventListener('click',closeStudentDetails);$('#student-details-close-bottom').addEventListener('click',closeStudentDetails);$('#student-details-dialog').addEventListener('click',event=>{if(event.target===$('#student-details-dialog'))closeStudentDetails()});
$('#pdf-report-button').addEventListener('click',async e=>{const button=e.currentTarget,message=$('#pdf-report-message');button.disabled=true;message.textContent='Gerando relatório...';try{const response=await fetch('/api/admin/report.pdf');if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Não foi possível gerar o relatório.')}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`relatorio-notas-${new Date().toISOString().slice(0,10)}.pdf`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message.textContent='Relatório gerado com sucesso.'}catch(error){message.textContent=error.message}finally{button.disabled=false}});
$('#calendar-import-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,file=$('#calendar-pdf').files[0],button=form.querySelector('button'),message=form.querySelector('.panel-message');if(!file)return;if(file.size>5*1024*1024){message.textContent='O PDF deve possuir no máximo 5 MB.';return}button.disabled=true;message.textContent='Lendo e validando o calendário...';try{const pdf_base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file)}),result=await api('/api/admin/calendar/import',{method:'POST',body:JSON.stringify({filename:file.name,pdf_base64})});message.textContent=`Calendário atualizado: ${result.imported} avaliações importadas.`;form.reset();await loadData()}catch(error){message.textContent=error.message}finally{button.disabled=false}});
$('#collective-score-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=$('#collective-save-button'),message=form.querySelector('.panel-message'),subject_id=$('#collective-subject').value,rows=[...$('#collective-score-table').querySelectorAll('tbody tr')],entries=rows.map(row=>{const entry={student_id:row.dataset.studentId};row.querySelectorAll('[data-field]').forEach(input=>entry[input.dataset.field]=input.value);return entry}),hasValues=entries.some(entry=>Object.entries(entry).some(([key,value])=>key!=='student_id'&&value!=='')),hasClears=entries.some(entry=>{const previous=cache.scores.find(score=>String(score.subject_id)===String(subject_id)&&String(score.student_id)===String(entry.student_id));if(!previous)return false;const empty=!Object.entries(entry).some(([key,value])=>key!=='student_id'&&value!=='');return empty});if(!hasValues&&!hasClears){message.textContent='Preencha pelo menos um resultado antes de salvar.';return}const payload=entries.filter(entry=>{const previous=cache.scores.find(score=>String(score.subject_id)===String(subject_id)&&String(score.student_id)===String(entry.student_id));const hasValue=Object.entries(entry).some(([key,value])=>key!=='student_id'&&value!=='');return hasValue||previous});button.disabled=true;message.textContent='Salvando lançamentos coletivos...';try{const result=await api('/api/admin/scores/bulk',{method:'POST',body:JSON.stringify({subject_id,entries:payload})});const cleared=Number(result.cleared||0);message.textContent=cleared?`${result.saved} salvos e ${cleared} limpos com sucesso.`:`${result.saved} resultados salvos com sucesso.`;await loadData();renderCollectiveScores()}catch(error){message.textContent=error.message}finally{button.disabled=false}});

// Mantém a lista de discentes da importação sincronizada com o cadastro principal.
new MutationObserver(()=>{const select=$('#pdf-score-student'),current=pdfImportStudentId||select.value;select.innerHTML=$('#score-student').innerHTML;select.value=current}).observe($('#score-student'),{childList:true});
function renderPdfScorePreview(entries){
  const container=$('#student-pdf-preview-table'),confirmButton=$('#student-pdf-confirm');
  confirmButton.disabled=false;confirmButton.textContent='Confirmar e salvar notas';$('#student-pdf-confirm-message').textContent='';
  container.innerHTML=`<div class="table-wrap"><table class="grade-table pdf-score-preview-table"><thead><tr><th>Importar</th><th>Disciplina</th><th>AVC / 1º TAF</th><th>AVF / 2º TAF</th><th>Trabalho / 3º TAF</th><th>Resultado</th></tr></thead><tbody>${entries.map(entry=>{
    const subject=cache.subjects.find(item=>String(item.id)===String(entry.subject_id));
    const previous=cache.scores.find(item=>String(item.student_id)===String(pdfImportStudentId)&&String(item.subject_id)===String(entry.subject_id));
    const apt=subject?.grading_mode==='apt',taf=subject?.grading_mode==='taf',defesa=isDefesaPessoal(subject),single=(subject?.exam_count===1&&subject?.grading_mode==='normal')||defesa;
    const valueOf=(field)=>entry[field]??previous?.[field]??'';
    const scoreInput=(field,max,disabled=false)=>disabled?'—':`<input data-field="${field}" type="number" min="0" max="${max}" step="0.01" inputmode="decimal" value="${valueOf(field)}" aria-label="${field} de ${esc(entry.subject)}">`;
    return`<tr data-subject-id="${entry.subject_id}"><td><input class="pdf-import-check" type="checkbox" checked aria-label="Importar ${esc(entry.subject)}"></td><td><strong>${esc(entry.subject)}</strong><small class="table-sub">Campos vazios no PDF mantêm a nota já lançada</small></td><td>${apt?'—':scoreInput('exam1',3,single)}</td><td>${apt?'—':scoreInput('exam2',taf?3:defesa?6:single?7:4)}</td><td>${apt?'—':scoreInput('work',taf||defesa?4:3)}</td><td>${apt?`<select data-field="status" aria-label="Resultado de ${esc(entry.subject)}"><option value="">Selecione</option><option${valueOf('status')==='Apto'?' selected':''}>Apto</option><option${valueOf('status')==='Inapto'?' selected':''}>Inapto</option></select>`:'Pontuação'}</td></tr>`;
  }).join('')}</tbody></table></div>`;
  $('#student-pdf-preview').hidden=false;
}
async function analyzePdfImport(event){
  event.preventDefault();
  const form=$('#student-pdf-score-form'),file=$('#student-score-pdf').files[0],student_id=$('#pdf-score-student').value;
  const button=$('#student-pdf-analyze-button'),message=form.querySelector('.panel-message');
  if(!student_id){message.textContent='Selecione o discente antes de importar o PDF.';$('#pdf-score-student').focus();showAdminFeedback({title:'Falta escolher o discente',eyebrow:'Atenção',message:'Selecione o discente antes de ler o PDF.',userAction:'Escolha o nome na lista e tente novamente.',tone:'warning'});return}
  if(!file){message.textContent='Selecione o arquivo PDF de notas.';$('#student-score-pdf').focus();showAdminFeedback({title:'Falta o arquivo PDF',eyebrow:'Atenção',message:'Selecione o arquivo PDF com as notas.',userAction:'Clique em escolher arquivo, selecione o PDF e tente novamente.',tone:'warning'});return}
  if(file.type&&file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){message.textContent='O arquivo selecionado precisa estar no formato PDF.';showAdminFeedback({title:'Arquivo inválido',eyebrow:'Atenção',message:'O arquivo precisa ser um PDF.',userAction:'Salve ou exporte o documento em PDF e envie novamente.',tone:'warning'});return}
  if(file.size>5*1024*1024){message.textContent='O PDF deve possuir no máximo 5 MB.';showAdminFeedback({title:'Arquivo muito grande',eyebrow:'Atenção',message:'O PDF ultrapassa o limite de 5 MB.',userAction:'Reduza o tamanho do arquivo ou divida o conteúdo e tente de novo.',tone:'warning'});return}
  $('#student-pdf-preview').hidden=true;$('#student-pdf-confirm-message').textContent='';
  button.disabled=true;button.textContent='Lendo o PDF...';message.textContent='Lendo as disciplinas e notas do PDF. Elas serão vinculadas ao discente selecionado. Aguarde...';
  try{
    const pdf_base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file)});
    const result=await api('/api/admin/student-scores/import',{method:'POST',body:JSON.stringify({action:'preview',student_id,pdf_base64})});
    pdfImportStudentId=student_id;renderPdfScorePreview(result.entries);
    message.textContent=`${result.entries.length} disciplina(s) reconhecida(s) para ${result.student.name} (matrícula ${student_id}). Confira a prévia antes de confirmar.`;
    if(result.user_action||(result.logs||[]).some(item=>String(item.level).toLowerCase()==='warning')){
      showAdminFeedback({title:'Prévia pronta, com avisos',eyebrow:'Conferência',message:`Foram reconhecidas ${result.entries.length} disciplina(s). Revise a prévia antes de salvar.`,userAction:result.user_action||'',logs:result.logs||[],tone:'warning'});
    }
    $('#student-pdf-preview').scrollIntoView({behavior:'smooth',block:'start'});
  }catch(error){
    message.textContent=error.message||'Não foi possível importar o PDF.';$('#student-pdf-preview').hidden=true;
    showAdminFeedback({title:'Não foi possível ler o PDF',eyebrow:'Erro na importação',message:error.message||'Não foi possível importar o PDF.',userAction:error.userAction||'Confira o arquivo e o discente selecionado, depois tente novamente.',logs:error.logs||[{level:'error',message:error.message||'Falha na leitura do PDF.'}],tone:'error'});
  }finally{
    button.disabled=false;button.textContent='Ler PDF e conferir notas';
  }
}
$('#student-pdf-score-form').addEventListener('submit',analyzePdfImport);
$('#pdf-score-student').addEventListener('change',()=>{pdfImportStudentId='';$('#student-pdf-preview').hidden=true;$('#student-pdf-preview-table').innerHTML=''});
$('#student-score-pdf').addEventListener('change',()=>{$('#student-pdf-preview').hidden=true;$('#student-pdf-preview-table').innerHTML=''});
$('#student-pdf-cancel').addEventListener('click',()=>{$('#student-pdf-preview').hidden=true;$('#student-pdf-preview-table').innerHTML='';$('#student-pdf-confirm-message').textContent=''});
async function confirmPdfImport(event){
  event?.preventDefault();
  event?.stopPropagation();
  const button=$('#student-pdf-confirm'),message=$('#student-pdf-confirm-message'),formMessage=$('#student-pdf-score-form .panel-message');
  if(!button||!message){window.alert('O botão de confirmação não foi carregado corretamente. Atualize a página e tente novamente.');return}
  if(button.dataset.saving==='true')return;
  button.dataset.saving='true';button.disabled=true;button.textContent='Salvando notas...';message.textContent='Preparando o lançamento das notas...';
  try{
    const student_id=pdfImportStudentId||$('#pdf-score-student')?.value;
    if(!student_id)throw new Error('Selecione novamente o discente, leia o PDF e tente salvar.');
    const rows=[...document.querySelectorAll('#student-pdf-preview-table tbody tr')];
    const entries=rows
      .filter(row=>row.querySelector('.pdf-import-check')?.checked)
      .map(row=>{const entry={subject_id:row.dataset.subjectId};row.querySelectorAll('[data-field]').forEach(input=>entry[input.dataset.field]=input.value);return entry});
    if(!entries.length)throw new Error('Marque pelo menos uma disciplina na prévia antes de salvar.');
    const student=cache.students.find(item=>String(item.id)===String(student_id));
    let saved=0;
    for(const entry of entries){
      message.textContent=`Salvando ${saved+1} de ${entries.length}: aguarde...`;
      await saveScoreResult({
        student_id,
        ...entry,
        observation:student?.observation||''
      });
      saved+=1;
      message.textContent=`Salvando notas: ${saved} de ${entries.length} concluída(s).`;
    }
    const success=`Salvo com sucesso: ${saved} disciplina(s) lançada(s).`;
    message.textContent=success;formMessage.textContent=`Notas salvas para o discente selecionado. ${success}`;
    button.textContent='Notas salvas';pdfImportStudentId=student_id;
    $('#student-score-pdf').value='';
    try{await loadData();$('#pdf-score-student').value=student_id}
    catch{formMessage.textContent=`${success} A tela não conseguiu atualizar automaticamente; clique em Atualizar para conferir.`}
    $('#student-pdf-preview').scrollIntoView({behavior:'smooth',block:'center'});
  }catch(error){
    const detail=error?.message||'Não foi possível salvar as notas.';
    const userAction=error?.userAction||'Confira o discente, as disciplinas e os valores mostrados na prévia. Depois tente novamente.';
    message.textContent=detail;formMessage.textContent=detail;button.textContent='Tentar salvar novamente';
    showAdminFeedback({title:'Erro ao salvar as notas',eyebrow:'Falha no lançamento',message:detail,userAction,logs:error?.logs||[{level:'error',message:detail}],tone:'error'});
  }finally{
    button.dataset.saving='false';button.disabled=false;
  }
}
const pdfConfirmButton=$('#student-pdf-confirm');
if(pdfConfirmButton)pdfConfirmButton.onclick=confirmPdfImport;
// O botão existe desde o carregamento da página; o vínculo direto garante o clique.

// Numera as relações administrativas sem alterar os valores usados pelo banco.
const numberedAdminSelects={
  '#score-student':'student',
  '#pdf-score-student':'student',
  '#score-subject':'subject',
  '#collective-subject':'subject',
  '#calendar-subject':'subject',
};
function numberAdminOptions(){
  for(const [selector,type] of Object.entries(numberedAdminSelects)){
    const select=$(selector);if(!select)continue;
    [...select.options].filter(option=>option.value).forEach((option,index)=>{
      let label=option.textContent.replace(/^\d+\.\s+/,'');
      if(type==='subject')label=label.replace(/\s+—\s+\d+\s+h\/a$/i,'');
      const numbered=`${index+1}. ${label}`;
      if(option.textContent!==numbered)option.textContent=numbered;
    });
  }
}
for(const selector of Object.keys(numberedAdminSelects)){
  const select=$(selector);
  if(select)new MutationObserver(numberAdminOptions).observe(select,{childList:true,subtree:true});
}
numberAdminOptions();

/* Organização do painel administrativo: reaproveita os formulários e APIs existentes. */
function activateAdminTab(tab){
  document.querySelectorAll('[data-admin-tab]').forEach(button=>{const active=button.dataset.adminTab===tab;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});
  document.querySelectorAll('[data-admin-tab-panel]').forEach(panel=>panel.hidden=panel.dataset.adminTabPanel!==tab);
}
setupAdminTabs=function(){
  const dashboard=$('#dashboard');if(!dashboard||dashboard.dataset.tabsReady)return;dashboard.dataset.tabsReady='true';
  const shell=document.createElement('div'),sidebar=document.createElement('aside'),content=document.createElement('div');shell.className='admin-workspace';sidebar.className='admin-sidebar';content.className='admin-tab-content';
  sidebar.innerHTML=`<div class="admin-sidebar-brand"><img src="assets/escudo-efas.png" alt="Escudo da EFAS"><div><strong>Controle de Notas</strong><small>1º Pelotão</small></div></div><nav class="admin-sidebar-nav" aria-label="Seções do painel"><button type="button" class="active" data-admin-tab="home" aria-pressed="true"><span aria-hidden="true">⌂</span><span>Início</span></button><button type="button" data-admin-tab="notes" aria-pressed="false"><span aria-hidden="true">✎</span><span>Lançamento de notas</span></button><button type="button" data-admin-tab="calendar" aria-pressed="false"><span aria-hidden="true">▦</span><span>Calendário de provas</span></button><button type="button" data-admin-tab="ranking" aria-pressed="false"><span aria-hidden="true">★</span><span>Ranking</span></button></nav>`;
  const groups=[{id:'home',elements:[]},{id:'notes',elements:['.score-mode-panel','.compact-grid','#collective-score-form','.pdf-score-import-panel','.student-subject-restriction']},{id:'calendar',elements:['#exam-form','#calendar-events-data','#calendar-import-form']},{id:'ranking',elements:['#ranking-data']}];
  for(const group of groups){const panel=document.createElement('section');panel.className='admin-tab-panel';panel.id=`admin-tab-${group.id}`;panel.dataset.adminTabPanel=group.id;panel.hidden=group.id!=='home';for(const selector of group.elements){const element=$(selector);if(!element)continue;if(selector==='#calendar-events-data'||selector==='#ranking-data'){const card=element.closest('.admin-panel');if(card)panel.append(card)}else panel.append(element)}content.append(panel)}
  content.querySelector('#admin-tab-home').innerHTML='<header class="admin-home-heading"><p class="eyebrow dark">Painel administrativo</p><h2>Visão geral</h2><p>Acesse rapidamente as rotinas de controle acadêmico.</p></header><div id="admin-home-actions" class="admin-home-actions"></div>';
  shell.append(sidebar,content);dashboard.append(shell);const head=$('.admin-dashboard-head'),warning=$('#initial-warning');if(head)content.prepend(head);if(warning)content.insertBefore(warning,content.querySelector('.admin-tab-panel'));
  sidebar.querySelectorAll('[data-admin-tab]').forEach(button=>button.addEventListener('click',()=>activateAdminTab(button.dataset.adminTab)));
};
function setupAdminSettings(user){
  const head=$('.admin-dashboard-head'),form=$('#password-form');if(!head||!form||$('#settings-dialog'))return;
  const account=document.createElement('div');account.className='admin-account-menu';account.innerHTML=`<span class="admin-user-label">${esc(user?.username||'Administrador')}</span><details><summary aria-label="Abrir opções da conta" title="Opções da conta">⚙</summary><button id="open-password-settings" type="button">Alterar senha</button></details>`;head.append(account);
  const dialog=document.createElement('dialog');dialog.id='settings-dialog';dialog.className='settings-dialog';dialog.innerHTML='<div class="settings-dialog-head"><div><p class="eyebrow dark">Conta</p><h2>Alterar senha</h2></div><button id="close-settings-dialog" class="dialog-close" type="button" aria-label="Fechar">×</button></div>';
  dialog.append(form);document.body.append(dialog);
  $('#open-password-settings').addEventListener('click',()=>{if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')});
  $('#close-settings-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
}
function renderStudentSearch(students=cache.students){
  const select=$('#student-search');if(!select)return;const selected=select.value;select.innerHTML='<option value="">Novo discente</option>'+(students||[]).map(student=>`<option value="${esc(student.id)}">${esc(student.name)} — ${esc(student.id)}</option>`).join('');select.value=selected;
  if(select.dataset.ready)return;select.dataset.ready='true';select.addEventListener('change',()=>{const student=(cache.students||[]).find(item=>String(item.id)===select.value),form=$('#student-form');if(!student){form.reset();form.elements.rank.value='Aluno CFS';return}form.elements.student_id.value=student.id;form.elements.name.value=student.name;form.elements.rank.value=student.rank;form.elements.access_code.value='';form.querySelector('.panel-message').textContent='Dados carregados. Informe um código individual apenas se quiser redefinir o acesso.'});
}
function renderDashboardHome(){
  const container=$('#admin-home-actions');if(!container)return;const cards=[['notes','✎','Lançamento de notas','Manual, coletivo, importação assistida e autorização do discente.'],['students','♙','Controle de discentes','Cadastrar, localizar e atualizar dados do pelotão.'],['calendar','▦','Calendário de provas','Cadastrar, alterar ou excluir avaliações.'],['ranking','★','Ranking','Consultar classificação e gerar relatório.']];container.innerHTML=cards.map(([tab,icon,title,text])=>`<button type="button" class="admin-home-card" data-home-tab="${tab}"><span aria-hidden="true">${icon}</span><strong>${title}</strong><small>${text}</small></button>`).join('');container.querySelectorAll('[data-home-tab]').forEach(button=>button.addEventListener('click',()=>activateAdminTab(button.dataset.homeTab)));
}
const baseLoadData=loadData;loadData=async function(){await baseLoadData();renderStudentSearch(cache.students);renderDashboardHome()};
dashboard=function(user){enforceAdminGroups();setupAdminTabs();setupStudentControlTab();setupNotesVisualLayout();setupAdminSettings(user);$('#login-panel').hidden=true;$('#dashboard').hidden=false;$('#initial-warning').hidden=!user.must_change_password;loadData()};

function renderProportionalRanking(){
  const container=$('#ranking-data'),rows=cache.ranking||[];if(!container)return;
  container.innerHTML=rows.length?`<div class="table-wrap"><table class="grade-table"><thead><tr><th>Posição</th><th>Discente</th><th>Pontos obtidos</th><th>Pontos distribuídos</th><th>Média</th><th>Aproveitamento</th><th>Observação</th></tr></thead><tbody>${rows.map(row=>`<tr><td><strong>${row.position}º</strong></td><td><button class="student-name-button" type="button" data-student-details="${esc(row.id)}" aria-label="Ver notas lançadas de ${esc(row.name)}">${esc(row.name)}</button><small class="table-sub">${esc(row.id)} • Clique no nome para consultar</small></td><td>${fmt(row.points)}</td><td>${fmt(row.distributed)}</td><td><strong>${fmt(row.average)}</strong></td><td>${fmt(row.percentage)}%</td><td>${esc(row.observation)||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhum discente cadastrado.</p>';
}
const loadedWithHome=loadData;loadData=async function(){await loadedWithHome();renderProportionalRanking()};

/* A verificação da sessão ocorre somente após a configuração final do painel. */
check();
